version: "3.8"

services:
  app:
    build: .
    container_name: travel-api-app
    ports:
      - "3000:3000"
    networks:
      - keploy-net

  keploy:
    image: ghcr.io/keploy/keploy:latest
    container_name: travel-api-keploy
    network_mode: "service:app"
    depends_on:
      - app
    tty: true
    stdin_open: true
    privileged: true
    command: record --container-name travel-api-app --network-name keploy-net --record-timer 1m

networks:
  keploy-net:
